#Qry1
SELECT TENKH
FROM KhachHang;

#Qry2
SELECT MASP,TENSP
FROM SanPham;

#Qry3
SELECT HO,TEN,DIACHI,DIENTHOAI
FROM NhanVien;

#Qry4
SELECT MAKH,TENKH,DCKHACH
FROM KhachHang
WHERE TENKH LIKE '%Cuong%';

#Qry5
SELECT TENKH,DTKHACH,DCKHACH
FROM KhachHang
WHERE DCKHACH LIKE '%An Duong Vuong%';

#Qry6
SELECT MASP,TENSP,DONGIA
FROM SanPham
WHERE TENSP LIKE '%Sharp%';

#Qry7
SELECT * FROM NhanVien
WHERE PHAI='M';

#Qry8
SELECT * FROM SanPham
WHERE DVT='Hop'AND DVT='Thung';

#Qry9
SELECT * FROM SanPham
WHERE DONGIA BETWEEN 1000000 AND 3000000;

#Qry10
SELECT * FROM SanPham
WHERE TENSP LIKE '%Sharp%' OR TENSP LIKE '%Toshiba%';

#Qry11
SELECT * FROM NhanVien
WHERE TEN LIKE '%Minh%';

#Qry12
SELECT MANV,HO,TEN,NGAYVL,DIACHI,MABP
FROM NhanVien
WHERE PHAI='F'AND MABP LIKE 'CH%';

#Qry13
SELECT * FROM NhanVien
WHERE YEAR(NGAYVL)-YEAR(NGAYSINH) BETWEEN 30 AND 40;

#Qry14
SELECT * FROM NhanVien
WHERE YEAR(CURDATE())-YEAR(NGAYVL)>=9;

#Qry15
SELECT * FROM HoaDon
WHERE DATE(NGAYGIAO)-DATE(NGAYHD)=5;

#Qry16
SELECT * FROM SanPham
WHERE DONGIA>=1000000;

#Cau 6
#Qry17
SELECT HO,TEN,SOHD,NGAYHD,MAKH
FROM NhanVien,HoaDon;

#Qry18
SELECT HoaDon.SOHD,HoaDon.NGAYHD,SanPham.TENSP,SanPham.DVT,SanPham.DONGIA,HoaDonCT.SOLUONG,HoaDon.MANV,NhanVien.TEN
FROM (NhanVien JOIN HoaDon ON NhanVien.MANV=HoaDon.MaNV)
    JOIN (SanPham JOIN HoaDonCT ON SanPham.MASP=HoaDonCT.MASP)
        ON HoaDon.SOHD=HoaDonCT.SOHD
WHERE NhanVien.TEN='Tram';

#Qry19
SELECT HoaDon.SOHD,HoaDon.NGAYHD,KhachHang.TENKH,NhanVien.TEN
FROM (HoaDon JOIN NhanVien ON HoaDon.MANV=NhanVien.MANV)
JOIN KhachHang ON HoaDon.MaKH = KhachHang.MAKH
WHERE QUARTER(HoaDon.NgayHD)=3 and year(NGAYHD)=2001;

#Qry20
SELECT KhachHang.TENKH, SanPham.TENSP,HoaDonCT.SOLUONG
FROM (KhachHang JOIN HoaDon ON KhachHang.MAKH=HoaDon.MAKH)
JOIN (SanPham JOIN HoaDonCT ON SanPham.MASP=HoaDonCT.MASP)
ON HoaDon.SOHD=HoaDonCT.SOHD
WHERE SOLUONG > 50;

#Qry21
SELECT NhanVien.TEN,HoaDon.SOHD,SanPham.TENSP,SanPham.DVT,HoaDonCT.SOLUONG,SanPham.DONGIA
FROM (NhanVien JOIN HoaDon ON NhanVien.MANV=HoaDon.MANV)
JOIN (SanPham JOIN HoaDonCT ON SanPham.MASP=HoaDonCT.MASP)
ON HoaDon.SOHD=HoaDonCT.SOHD;

#Qry22
SELECT HoaDonCT.SOHD,HoaDon.NGAYHD,SanPham.TENSP,
       ((1-GIAMGIA)*(SOLUONG*DONGIA)) AS 'ThanhTien'
FROM (HoaDon JOIN HoaDonCT ON HoaDon.SOHD=HoaDonCT.SOHD)
JOIN SanPham  ON SanPham.MASP=HoaDonCT.MASP;

# Tinh Doanh thu nam 2001
SELECT SanPham.TENSP,SUM((1-GIAMGIA/100)*(SOLUONG*DONGIA)) AS DoanhThu
FROM (HoaDonCT JOIN HoaDon ON HoaDonCT.SOHD=HoaDon.SOHD)
JOIN SanPham ON HoaDonCT.MASP=SanPham.MASP
WHERE YEAR(HoaDon.NGAYHD)=2001
GROUP BY SanPham.TENSP;
